# Site settings
title: "Jefferson Araujo Resume"
description: "I am a Computer Science graduate and currently pursuing a Master's degree in Artificial Intelligence with a focus on time series forecasting at Cin-UFPE. Since 2010, I have been working in the corporate solutions development market and have gained extensive experience in different areas."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Jefferson O. A. de Araujo"
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "joaa@cin.ufpe.br"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a Computer Science graduate and currently pursuing a Master's degree in Artificial Intelligence with a focus on time series forecasting at Cin-UFPE. Since 2010, I have been working in the corporate solutions development market and have gained extensive experience in different areas.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/euojeff"
  resume_twitter_url:           "http://twitter.com/euojeff"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/euojeff"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
